- name: Deploy Application
    hosts: all
    vars:
    tasks:
      - name: download and unarchive techtestservian app
        become: yes
        unarchived:
          src: https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_darwin.zip
          dest: /usr/local/bin
          remote_src: yes

      - name: install and run
        become: yes
        shell: 
          cmd: cd /usr/local/bin/dist
              ./TechTestApp

      - name: run template
        file:
        
      - name: run app config
        file:
          path:
          state: started
          enabled: yes
        
      - name: run and serve app
        become: yes
        shell:
          cmd:
              ./TechTestApp serve