- name: Deploy Application
  hosts: all
  vars:
  tasks:
    - name: Download TechTestApp
      become: yes
      unarchive:
        src: https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_linux64.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: Move the App to /etc/app
      become: yes
      shell: |
        mkdir /etc/app
        cp -r /usr/local/bin/dist/* /etc/app/

    - name: generate conf.toml
      script: database.sh

    - name: copy conf.toml into etc/app file
      become: yes
      copy:
        src: conf.toml
        dest: /etc/app/

    - name: upload service file
      become: yes
      template:
        src: templates/techtestapp.service
        dest: "/usr/lib/systemd/system/techtestapp.service"

    - name: ensure systemd is running
      become: yes
      service:
        name: techtestapp
        state: started
        enabled: yes

    - name: automate db deployment
      become: yes
      shell: ./TechTestApp updatedb -s
      args:
        chdir: /etc/app
